[package]
name = "orbits"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.28"
jwalk = "0.6.0"

[dev-dependencies]
zip = "0.5.13"